### ISSUE TITLE
Add configuration file example

### ISSUE THREAD

**Issue by paulolieuthier** [DMOJ/docs#2]
I can't run dmoj without a configuration file and I don't know how to build one.

**Comment by Xyene** [comment]
Are you intending to run the entire DMOJ site interface (i.e. an instance of <https://dmoj.ca>), or just the judge component of it for local grading or similar purposes? The configuration file(s) differ based on which of these goals you're aiming for.

**Comment by paulolieuthier** [comment]
The whole site, I believe. But it would be helpful to now it for the judge component, for sure.

**Comment by paulolieuthier** [comment]
@Xyene please, help me. I'd like to use DMOJ in my University (I'm a monitor). It's the only one I found that supports Haskell.

**Comment by Xyene** [comment]
Hi, sorry for the delay. The DMOJ is fairly tricky to install, mainly because it wasn't originally intended to be installed in more places than the dmoj.ca server. @WallE256 managed to set up his own instance of the site, and since then we've made installation a fair bit easier. It's still complex and undocumented though. WallE256 has started writing some docs [here](https://github.com/WallE256/docs/blob/master/site.md), though I think the fastest way to get you set up is if we can chat - it would be easier to fix up the issues that will inevitably crop up while installing (the DMOJ system is stable *once* installed, though). If you are comfortable with chatting in IRC, we're #dmoj on esper.net.

**Comment by paulolieuthier** [comment]
Thanks for your help. I hope I can get it to work and eventually help improving DMOJ. I actually entered the #dmoj room before filing this issue, but on Freenode (and it was empty). I'll be on #dmoj on esper.net whenever I have time, so we can chat.

**Comment by Xyene** [comment]
We've added documentation on running the judging servers, along with sample problem data files. And thanks to @WallE256, there are now instructions on installing the DMOJ site in its entirety in [site.md](https://github.com/DMOJ/docs/blob/master/site.md) - that should help with the tricky bits.

It seems that our schedules haven't yet overlapped, but I'll be on IRC for today, and if I'm not feel free to send me an email at <xyene@dmoj.ca> so I can hop on IRC.

Good luck!

**Comment by paulolieuthier** [comment]
Thanks! I'll try it and report errors if found. Thank you again.
