### ISSUE TITLE
PDF Generation

### ISSUE THREAD

**Issue by devlphj** [DMOJ/docs#31]
I refer a lot on 'dmoj.readthedocs.io' when installing the site or adminstering(adding problems).
A printed version of the manual will be really helpful when doing those jobs.
Can you select the 'Generate PDF' on the read the docs admin panel?

**Comment by Xyene** [comment]
We use mkdocs to generate the docs (so we can write Markdown instead of reStructuredText), and [according to the readthedocs docs](https://docs.readthedocs.io/en/latest/builds.html#how-we-build-documentation),

> As MkDocs doesn’t support automatic PDF generation, Read the Docs cannot create a PDF version of your documentation with the Mkdocs option.

A solution would be switching to RST, but RST is foreign to most (all?) of the dev team, so it'd end up slowing the addition of docs (which could use some work in the first place).

I suppose an alternative on your end would be to run `pandoc` over our Markdown files to convert them to RST, then build the project with Sphinx to output to PDF. Definitely not as ideal as readthedocs supporting PDF outputs out of the box, though.
